"""Generate <target>/.opencode/opencode.jsonc from a validated danno.toml.

Ports the agent-tier mapping from the Bash `tools/gen-opencode-config`. Tier-1 of
the automation policy: a new file is written freely on first run (nothing to
clobber); a later run that would change an existing file returns a diff for
approval (the CLI requires --apply to overwrite it).
"""

from __future__ import annotations

import difflib
import json
import re
from dataclasses import dataclass, field
from enum import StrEnum
from pathlib import Path
from typing import Any
from urllib.parse import urlsplit

from .schema import (
    AgentSpec,
    DannoConfig,
    InertBackend,
    LlamacppBackend,
    Model,
    OllamaBackend,
    OpenAIBackend,
    Overrides,
)

_HEADER = (
    "// Generated by book-em-danno (danno config generate) from danno.toml. Edit danno.toml.\n"
    "// models.<tag>.limit.context : OpenCode's CLIENT-SIDE belief of the window, used to\n"
    "//                              trim/compact the conversation. From danno's context_budget.\n"
    "//                              It does NOT set Ollama's real window: under /v1 Ollama\n"
    "//                              loads the model at its FULL context (a body num_ctx is\n"
    "//                              ignored). The real window / RAM lever is an Ollama\n"
    "//                              Modelfile variant, not an opencode.jsonc key.\n"
    "// models.<tag>.limit.output  : tokens OpenCode reserves for the reply\n"
    "//                              (usable input is roughly context - output).\n"
    "// models.<tag>.options.reasoningEffort : forwarded raw into the /v1 request body where\n"
    "//                              Ollama honors it. 'none' disables the thinking trace\n"
    "//                              (faster; avoids the opencode #21903 reasoning-field hang).\n"
    "// opencode ALWAYS streams (stream:true is hardcoded); there is no stream/thinking key.\n"
    "// Local agents need a TOOL-CAPABLE model (gemma3:1b cannot tool-call).\n"
)

_LLAMACPP_STUB = "llama.cpp backend not yet implemented (stubbed slot in danno.toml)"

# claurst's built-in provider id (and display name) for each danno backend. claurst is
# launched `-m <provider>/<tag>` and resolves <provider> against its OWN registry
# (ollama via OLLAMA_HOST, nvidia via NVIDIA_API_KEY), so this is NOT the danno backend
# name that model_ref() emits for opencode. openai-kind backends are mapped by host.
_CLAURST_PROVIDER_NAMES = {"ollama": "Ollama", "nvidia": "Nvidia"}
_NVIDIA_NIM_HOST = "integrate.api.nvidia.com"

# Partial-ownership markers. danno owns only the region between begin/end; everything
# outside (user keys/comments in jsonc; other frontmatter keys + the body in md) is
# preserved verbatim on merge. One primitive, two formats — JSONC `//` comments inside
# the top-level object, YAML `#` comments inside the `---` frontmatter fence.
_JSONC_BEGIN = (
    "// >>> danno:managed — generated from danno.toml; edits between the danno markers "
    "are overwritten >>>"
)
_JSONC_END = "// <<< danno:managed <<<"
_MD_BEGIN = (
    "# >>> danno:managed — model assignment from danno.toml; edits between the danno "
    "markers are overwritten >>>"
)
_MD_END = "# <<< danno:managed <<<"

# Fields danno writes into md frontmatter (where markdown wins over JSON) rather than
# the opencode.jsonc agent block. Phase 1 routes only `model` (the guaranteed lever);
# scalar tuning routing is a trivial follow-on.
_ROUTED_TO_MD = frozenset({"model"})


class Action(StrEnum):
    WROTE = "wrote"
    UNCHANGED = "unchanged"
    DIFF = "diff"  # differs from the existing file; not written (needs --apply)


@dataclass
class GenerateResult:
    action: Action
    path: Path
    content: str
    diff: str = ""
    warnings: list[str] = field(default_factory=list)


def deep_merge(base: dict[str, Any], override: dict[str, Any]) -> dict[str, Any]:
    """Return a new dict: `override` deep-merged over `base`. Nested objects merge
    recursively; scalars and arrays (and any non-dict) REPLACE wholesale — arrays do
    not element-merge. This is the escape-hatch merge for `[<element>.overrides.<h>]`
    (see schema.Overrides): danno builds a block, then the override wins on any key it
    names, leaving danno's other keys intact."""
    out = dict(base)
    for key, value in override.items():
        existing = out.get(key)
        if isinstance(existing, dict) and isinstance(value, dict):
            out[key] = deep_merge(existing, value)
        else:
            out[key] = value
    return out


def _override(overrides: Overrides | None, harness: str) -> dict[str, Any] | None:
    """The override payload for `harness` ('opencode'/'claurst'), or None if unset."""
    if overrides is None:
        return None
    payload: dict[str, Any] | None = getattr(overrides, harness)
    return payload or None


def resolve_limits(model: Model) -> dict[str, int]:
    """The `limit` block ({context, output}) for a model, from its model-level budget.

    Model-level (not backend-level): `context_budget`/`output_limit` live on the model.
    Validated present at config load for ollama/openai backends (schema
    `_check_references`), so both are non-None here for any model that emits a limit."""
    if model.context_budget is None or model.output_limit is None:
        # Defensive: the schema validator guarantees this for limit-emitting backends.
        raise ValueError("model missing context_budget/output_limit (should fail at load)")
    return {"context": model.context_budget, "output": model.output_limit}


# Override payload keys that steer egress/auth — overriding them can weaken the sandbox
# security contract (see memory: sandbox-security-contract-fail-loud), so they get a loud
# warning even though the override still applies (it is the developer's own diffed config).
_SENSITIVE_OVERRIDE_KEYS = frozenset({"baseurl", "base_url", "apikey", "api_key"})


def _sensitive_override_paths(payload: dict[str, Any], path: str = "") -> list[str]:
    """Dotted paths in an override payload that touch egress/auth-sensitive keys."""
    hits: list[str] = []
    for key, value in payload.items():
        here = f"{path}.{key}" if path else key
        if key.lower() in _SENSITIVE_OVERRIDE_KEYS:
            hits.append(here)
        if isinstance(value, dict):
            hits.extend(_sensitive_override_paths(value, here))
    return hits


def override_warnings(config: DannoConfig, harness: str) -> list[str]:
    """Loud transparency (Working Rule 8) for every `[<element>.overrides.<harness>]` in
    effect: the diff shows the resulting value, this names WHICH danno-generated block a
    user override supersedes, and flags any egress/auth-sensitive key it touches. The
    peer of `agent_markdown_collisions` / `claurst_agent_unmapped_warnings`; called by
    `generate` (opencode) and `generate_claurst` (claurst)."""
    warnings: list[str] = []

    def check(overrides: Overrides | None, loc: str) -> None:
        payload = _override(overrides, harness)
        if payload is None:
            return
        keys = ", ".join(sorted(payload))
        warnings.append(
            f"override[{harness}] {loc}: overrides danno-generated config ({keys}) — "
            "verify the diff; danno's own value(s) are superseded."
        )
        for sensitive in _sensitive_override_paths(payload):
            warnings.append(
                f"override[{harness}] {loc}: sets egress/auth-sensitive '{sensitive}' — "
                "verify this does not weaken the sandbox contract."
            )

    check(config.defaults.overrides, "defaults")
    for name, backend in config.backends.items():
        check(getattr(backend, "overrides", None), f"backend '{name}'")
    for name, model in config.models.items():
        check(model.overrides, f"model '{name}'")
    for name, value in config.agents.items():
        if isinstance(value, AgentSpec):
            check(value.overrides, f"agent '{name}'")
    return warnings


def model_ref(config: DannoConfig, model_name: str) -> str:
    """Resolve a model name to its OpenCode `<provider>/<model>` reference.

    Public so the validator's matrix generator can label and `-m`-drive each model
    variant with the exact ref OpenCode expects (e.g. `ollama/gemma3:27b`)."""
    model = config.models[model_name]
    backend = config.backends[model.backend]
    if isinstance(backend, InertBackend):
        # danno dials nothing: the harness serves this model itself and selects it
        # by its native flag (claude's --model). The `tag` IS that raw id/alias, so
        # the ref is the bare tag — no `<backend>/` provider prefix.
        if not model.tag:
            raise ValueError(f"model '{model_name}' on inert backend needs a 'tag'")
        return model.tag
    if isinstance(backend, OllamaBackend | OpenAIBackend):
        if not model.tag:
            raise ValueError(f"model '{model_name}' on {backend.kind} backend needs a 'tag'")
        return f"{model.backend}/{model.tag}"
    if isinstance(backend, LlamacppBackend):
        raise NotImplementedError(_LLAMACPP_STUB)
    raise ValueError(f"unknown backend kind for model '{model_name}'")


def agent_ref(config: DannoConfig, value: str) -> str:
    """Resolve an [agents] model value to an OpenCode model ref.

    A value with a '/' is a raw OpenCode ref (e.g. `anthropic/claude-sonnet-4-6`),
    passed through verbatim — OpenCode knows built-in cloud models via its catalog
    and launch-time auth, so danno emits no provider block for them. A value without
    a '/' names a [models] entry resolved via `model_ref`."""
    if "/" in value:
        return value
    return model_ref(config, value)


def agent_model_name(value: str | AgentSpec) -> str | None:
    """The danno model NAME (or raw ref) an [agents] value selects, in either form.

    The string shorthand IS the name; the rich form carries it in `.model` (which may
    be unset when the agent only pins mode/permission). Distinct from `agent_ref`,
    which RESOLVES a name to its OpenCode ref."""
    return value if isinstance(value, str) else value.model


def claurst_provider_id(config: DannoConfig, model_name: str) -> str:
    """The claurst built-in provider id that serves a danno [models] entry.

    claurst resolves `-m <provider>/<tag>` against its own provider registry, so the
    provider here is claurst's (ollama / nvidia / …), NOT the danno backend name that
    `model_ref` emits for OpenCode. ollama-kind backends map to `ollama`; openai-kind
    backends are mapped by host (NVIDIA NIM → `nvidia`). Unmapped hosts raise."""
    backend = config.backends[config.models[model_name].backend]
    if isinstance(backend, OllamaBackend):
        return "ollama"
    if isinstance(backend, OpenAIBackend):
        host = urlsplit(backend.base_url).hostname or ""
        if host == _NVIDIA_NIM_HOST:
            return "nvidia"
        raise NotImplementedError(
            f"model '{model_name}': no claurst provider mapping for openai host "
            f"'{host}' yet (only NVIDIA NIM at {_NVIDIA_NIM_HOST} is mapped)."
        )
    raise NotImplementedError(_LLAMACPP_STUB)


def claurst_model_ref(config: DannoConfig, model_name: str) -> str:
    """The `-m` ref danno passes to claurst: `<claurst_provider>/<tag>`.

    Sibling of `model_ref` (which yields the OpenCode `<backend>/<tag>` ref)."""
    model = config.models[model_name]
    if not model.tag:
        raise ValueError(f"model '{model_name}' needs a 'tag' for claurst")
    return f"{claurst_provider_id(config, model_name)}/{model.tag}"


def generate_claurst_models(config: DannoConfig) -> dict[str, Any]:
    """Build claurst's model-registry overlay (models.dev api.json shape) from danno.toml.

    claurst gates BOTH the outgoing tools array and the context-meter window on a
    model's registry entry: an uncatalogued model gets a wrong window, and an overlay
    that omits `tool_call` silently disables tools (it defaults to false). danno owns
    the truth, so it emits this overlay — pointed at via `CLAURST_MODELS_PATH` — which
    registers every [models] entry with `tool_call: true` and danno's context/output
    budget, grouped by claurst provider. The model id is the danno `tag` (what the
    endpoint expects); `reasoning` is set for a non-`none` reasoning_effort. Mirrors the
    opencode generator's models block."""
    providers: dict[str, Any] = {}
    for name, model in config.models.items():
        backend = config.backends[model.backend]
        if not isinstance(backend, OllamaBackend | OpenAIBackend):
            raise NotImplementedError(_LLAMACPP_STUB)
        if not model.tag:
            raise ValueError(f"model '{name}' needs a 'tag' for claurst")
        provider = claurst_provider_id(config, name)
        entry: dict[str, Any] = {
            "id": model.tag,
            "name": name,
            "tool_call": True,
            "limit": resolve_limits(model),
        }
        if model.reasoning_effort is not None and model.reasoning_effort != "none":
            entry["reasoning"] = True
        model_ov = _override(model.overrides, "claurst")
        if model_ov is not None:
            entry = deep_merge(entry, model_ov)
        if provider not in providers:
            prov_entry: dict[str, Any] = {
                "id": provider,
                "name": _CLAURST_PROVIDER_NAMES.get(provider, provider),
                "env": [],
                "models": {},
            }
            backend_ov = _override(getattr(backend, "overrides", None), "claurst")
            if backend_ov is not None:
                prov_entry = deep_merge(prov_entry, backend_ov)
            providers[provider] = prov_entry
        providers[provider]["models"][model.tag] = entry
    return providers


def claurst_agent_ref(config: DannoConfig, value: str) -> str:
    """Resolve an [agents] model value to a claurst `<provider>/<tag>` ref.

    The claurst counterpart of `agent_ref`: a value with a '/' is a raw claurst ref
    (e.g. `anthropic/claude-opus-4-6`) passed through verbatim — claurst knows built-in
    cloud models via its own provider registry — while a bare name resolves a [models]
    entry through `claurst_model_ref` (claurst's provider id, NOT the opencode backend)."""
    if "/" in value:
        return value
    return claurst_model_ref(config, value)


# danno AgentSpec field -> claurst AgentDefinition field. `model` is handled separately
# (it needs ref resolution); these copy across verbatim. `hidden` inverts to `visible`.
_CLAURST_AGENT_FIELD_MAP = {
    "description": "description",
    "prompt": "prompt",
    "temperature": "temperature",
    "steps": "max_turns",
    "color": "color",
}
# AgentSpec fields claurst's AgentDefinition has no home for. Set-but-unmapped → warn
# loud rather than silently drop (Working Rule 8): `mode`/`top_p` have no claurst concept,
# `disable` differs from `visible` (hide ≠ remove), and `permission` is an opencode-shaped
# dict that does not translate to claurst's single `access` enum.
_CLAURST_AGENT_UNMAPPED = frozenset({"mode", "top_p", "disable", "permission"})


def generate_claurst_agents(config: DannoConfig) -> dict[str, Any]:
    """Build claurst's `settings.json` `agents` map from danno.toml [agents].

    The claurst sibling of the opencode `agent.<name>` block (`_danno_doc`): each danno
    agent becomes a claurst `AgentDefinition`. The string shorthand carries only a model;
    the rich `AgentSpec` maps field-by-field via `_CLAURST_AGENT_FIELD_MAP` (notably
    `steps` → `max_turns`, the Bug-2 turn lever, and `hidden` → `visible` inverted). The
    `model`, when set, resolves through `claurst_agent_ref`. Fields claurst can't express
    (`_CLAURST_AGENT_UNMAPPED`) are skipped here and surfaced by
    `claurst_agent_unmapped_warnings`. An agent left with no claurst-side fields is dropped,
    mirroring the opencode generator."""
    agents: dict[str, Any] = {}
    for agent, value in config.agents.items():
        if isinstance(value, str):
            agents[agent] = {"model": claurst_agent_ref(config, value)}
            continue
        entry: dict[str, Any] = {}
        if value.model is not None:
            entry["model"] = claurst_agent_ref(config, value.model)
        for danno_field, claurst_field in _CLAURST_AGENT_FIELD_MAP.items():
            v = getattr(value, danno_field)
            if v is not None:
                entry[claurst_field] = v
        if value.hidden is not None:
            entry["visible"] = not value.hidden
        agent_ov = _override(value.overrides, "claurst")
        if agent_ov is not None:
            entry = deep_merge(entry, agent_ov)
        if entry:  # drop an agent that mapped to nothing claurst understands
            agents[agent] = entry
    return agents


def claurst_agent_unmapped_warnings(config: DannoConfig) -> list[str]:
    """Loud warnings (Working Rule 8) for [agents] fields claurst cannot express.

    `generate_claurst_agents` silently skips fields with no `AgentDefinition` home; this
    surfaces them so a danno.toml setting is never quietly lost when targeting claurst."""
    warnings: list[str] = []
    for agent, value in config.agents.items():
        if isinstance(value, str):
            continue
        unmapped = sorted(_danno_agent_fields(value) & _CLAURST_AGENT_UNMAPPED)
        if unmapped:
            shown = ", ".join(unmapped)
            warnings.append(
                f"agent '{agent}': danno.toml sets {shown}, which claurst's agent "
                "definition has no field for — the value(s) will be ignored for claurst. "
                "Use steps (→max_turns), prompt, temperature, color, or hidden instead."
            )
    return warnings


def _danno_doc(
    config: DannoConfig,
    md_routed_agents: frozenset[str],
    *,
    disable_title: bool = False,
    agent_steps: dict[str, int] | None = None,
) -> dict[str, Any]:
    """The danno-owned opencode.jsonc members as a dict (no markers/braces).

    `md_routed_agents` are agents whose `model` danno writes into their `.md`
    frontmatter (where markdown wins) instead of the jsonc `agent.<name>` block — so
    their model is omitted here, and an agent left with no jsonc fields is dropped.

    `disable_title` emits opencode's `agent.title.disable` to switch off its per-session
    thread-title generator. The validator sets it for sweeps so throwaway sessions never
    spend the local default model on naming threads (see `sweep.prepare_workspace`)."""
    # Model NAMES the agent map selects, in either [agents] form (raw refs included).
    used_models = {
        name for value in config.agents.values() if (name := agent_model_name(value)) is not None
    }

    # Emit a provider block for every ollama-kind model DEFINED in danno.toml, not
    # just those assigned to an agent — so the whole catalog shows in opencode's
    # model picker (the user switches models interactively, beyond the agent map).
    providers: dict[str, dict[str, Any]] = {}
    for model_name in sorted(config.models):
        model = config.models[model_name]
        backend = config.backends[model.backend]
        if isinstance(backend, LlamacppBackend):
            raise NotImplementedError(_LLAMACPP_STUB)
        if isinstance(backend, OllamaBackend | OpenAIBackend):
            # Both render an @ai-sdk/openai-compatible provider; they differ only in
            # auth and labelling: ollama is local/no-auth (dummy apiKey = the backend
            # name), openai-compatible carries an env-substituted key.
            if isinstance(backend, OllamaBackend):
                provider_name = f"{model.backend} (local)"
                api_key = model.backend
                model_label = f"{model.tag} (local)"
            else:  # OpenAIBackend — secret arrives at runtime, never written here
                provider_name = model.backend
                api_key = f"{{env:{backend.api_key_env}}}"
                model_label = model.tag or ""
            if model.backend not in providers:
                provider: dict[str, Any] = {
                    "npm": "@ai-sdk/openai-compatible",
                    "name": provider_name,
                    "options": {"baseURL": backend.base_url, "apiKey": api_key},
                    "models": {},
                }
                # backend-level escape hatch: e.g. npm = "@ai-sdk/openai" for an OpenAI
                # native (o-series) provider. Applied once, before models are attached.
                backend_ov = _override(backend.overrides, "opencode")
                if backend_ov is not None:
                    provider = deep_merge(provider, backend_ov)
                providers[model.backend] = provider
            provider = providers[model.backend]
            entry: dict[str, Any] = {
                "name": model_label,
                # Fixed: the openai-compatible provider requires this capability key,
                # and every danno-configured model must be tool-capable anyway (opencode
                # advertises the agent's tools on every request regardless of its value).
                "tool_call": True,
                "limit": resolve_limits(model),
            }
            if model.reasoning_effort is not None:
                # camelCase is load-bearing: @ai-sdk/openai-compatible spreads model
                # options raw into the body, and a snake_case key gets clobbered.
                entry["options"] = {"reasoningEffort": model.reasoning_effort}
            # model-level escape hatch: e.g. options.max_completion_tokens (o-series).
            # deep_merge keeps reasoningEffort while adding/overriding sibling options.
            model_ov = _override(model.overrides, "opencode")
            if model_ov is not None:
                entry = deep_merge(entry, model_ov)
            provider["models"][model.tag] = entry

    # Each agent renders to its opencode.jsonc `agent.<name>` block. The string
    # shorthand is just a model; the rich form's other fields are emitted verbatim
    # (its `model`, if set, resolved to a ref the same way). For an md-routed agent
    # the model is written to its `.md` frontmatter instead, so it is omitted here.
    agent_block: dict[str, dict[str, Any]] = {}
    for agent, value in config.agents.items():
        routed = agent in md_routed_agents
        if isinstance(value, str):
            if routed:
                continue  # only carried a model; the .md now owns it → no jsonc block
            agent_block[agent] = {"model": agent_ref(config, value)}
            continue
        # `overrides` is danno's escape-hatch container, not an opencode agent field —
        # exclude it from the verbatim dump and apply it as a merge below instead.
        entry = value.model_dump(exclude_none=True, exclude={"overrides"})
        if routed:
            entry.pop("model", None)  # routed to the .md frontmatter
        elif value.model is not None:
            entry["model"] = agent_ref(config, value.model)
        agent_ov = _override(value.overrides, "opencode")
        if agent_ov is not None:
            entry = deep_merge(entry, agent_ov)
        if entry:  # drop an agent left with no jsonc-side fields
            agent_block[agent] = entry

    default_agent = config.defaults.default_agent
    default_model = (
        agent_model_name(config.agents[default_agent]) if default_agent in config.agents else None
    )
    if default_model is not None:
        main_ref = agent_ref(config, default_model)
    elif config.models:
        main_ref = model_ref(config, sorted(config.models)[0])
    else:
        main_ref = ""

    # The small/cheap model: the first ollama-backed used model, else the main model.
    # Raw refs (anthropic/…) aren't [models] entries, so skip them — they have no
    # local backend to qualify as the small model.
    small_ref = main_ref
    for value in sorted(used_models):
        if "/" in value or value not in config.models:
            continue
        if isinstance(config.backends[config.models[value].backend], OllamaBackend):
            small_ref = model_ref(config, value)
            break

    doc: dict[str, Any] = {
        "$schema": "https://opencode.ai/config.json",
        "default_agent": default_agent,
        "model": main_ref,
        "small_model": small_ref,
    }
    if providers:
        doc["provider"] = providers
    if disable_title:
        # opencode's title generator is a reserved pseudo-agent; `disable` stops the
        # per-session "name this thread" call (verified on the wire to otherwise hit the
        # local default model). A real "title" agent in danno.toml would be unusual; this
        # deliberately wins for the sweep config that requests it.
        agent_block["title"] = {"disable": True}
    # Runaway-gate polite-stop: set `steps` (opencode's per-agent iteration cap) on the
    # named agent(s) — bench passes {run-agent: max_turns}. Soft/advisory (DoR §3.4), so the
    # external watchdog is still the real bound; this just asks opencode to stop first.
    for agent_name, steps in (agent_steps or {}).items():
        agent_block.setdefault(agent_name, {})["steps"] = steps
    doc["agent"] = agent_block
    # OpenCode npm plugins: a bare package string, or the documented
    # [package, config] tuple when the plugin takes options. Omitted entirely for
    # plugin-less projects to keep the output minimal/stable.
    if config.npm:
        doc["plugin"] = [
            p.package if p.config is None else [p.package, p.config] for p in config.npm
        ]
    # top-level escape hatch for opencode.jsonc's danno-owned keys ($schema,
    # default_agent, model, small_model, or a wholly new top-level key).
    defaults_ov = _override(config.defaults.overrides, "opencode")
    if defaults_ov is not None:
        doc = deep_merge(doc, defaults_ov)
    return doc


def _region_inner(
    config: DannoConfig,
    md_routed_agents: frozenset[str],
    *,
    disable_title: bool = False,
    agent_steps: dict[str, int] | None = None,
) -> list[str]:
    """The lines danno owns inside the opencode.jsonc managed region: the header
    comments + the JSON member lines (2-space indented, no enclosing braces)."""
    doc = _danno_doc(config, md_routed_agents, disable_title=disable_title, agent_steps=agent_steps)
    member_lines = json.dumps(doc, indent=2).splitlines()[1:-1]  # drop the `{` / `}`
    header_lines = ["  " + ln for ln in _HEADER.rstrip("\n").splitlines()]
    return header_lines + member_lines


def _fresh_jsonc(region_inner: list[str]) -> str:
    """A complete opencode.jsonc written from scratch: the danno region wrapped in
    markers inside the top-level object, with no user members."""
    lines = ["{", "  " + _JSONC_BEGIN, *region_inner, "  " + _JSONC_END, "}"]
    return "\n".join(lines) + "\n"


def _has_jsonc_member(after: list[str]) -> bool:
    """True if the lines after the managed region hold a JSON member before the closing
    brace — i.e. the managed block's last member needs a trailing comma."""
    for ln in after:
        s = ln.strip()
        if not s or s == "}" or s.startswith("//"):
            continue
        return True
    return False


def _merge_jsonc(existing: str, region_inner: list[str]) -> str:
    """Splice danno's managed region into an existing opencode.jsonc, preserving every
    byte outside the markers (user keys + comments). A file with no markers is rewritten
    wholesale (this installs the markers; same blast radius as the prior overwrite-only
    behaviour) so that every subsequent run is an in-place region merge."""
    lines = existing.splitlines()
    begin = end = None
    for i, ln in enumerate(lines):
        if _JSONC_BEGIN in ln:
            begin = i
        elif _JSONC_END in ln and begin is not None:
            end = i
            break
    if begin is None or end is None:
        return _fresh_jsonc(region_inner)
    after = lines[end + 1 :]
    inner = list(region_inner)
    if _has_jsonc_member(after):
        inner[-1] = inner[-1] + ","  # last danno member needs a comma before user keys
    merged = [*lines[:begin], "  " + _JSONC_BEGIN, *inner, "  " + _JSONC_END, *after]
    return "\n".join(merged) + "\n"


def render_config(
    config: DannoConfig,
    *,
    md_routed_agents: frozenset[str] = frozenset(),
    disable_title: bool = False,
    agent_steps: dict[str, int] | None = None,
) -> str:
    """The full opencode.jsonc danno would write fresh (danno region wrapped in markers).

    `md_routed_agents` omit their `model` here because danno writes it into their `.md`
    frontmatter instead (see `generate_md`). `disable_title` emits `agent.title.disable`;
    `agent_steps` sets the runaway-gate polite-stop `steps` per agent (see `_danno_doc`)."""
    return _fresh_jsonc(
        _region_inner(
            config, md_routed_agents, disable_title=disable_title, agent_steps=agent_steps
        )
    )


# Markdown agent defs live under either dir (docs use plural, ADOS uses singular);
# OpenCode loads BOTH, so danno scans both. danno NEVER writes these files.
_AGENT_DIRS = ("agents", "agent")

_FRONTMATTER_KEY = re.compile(r"([A-Za-z_][\w-]*):")


def _frontmatter_keys(md_text: str) -> set[str]:
    """The top-level YAML frontmatter keys of a markdown agent def.

    Only the key NAMES are needed (to detect which fields a markdown def sets), so a
    top-level `^key:` scan of the leading `---`-fenced block is enough — no YAML
    dependency, and nested/indented keys are intentionally skipped."""
    lines = md_text.splitlines()
    if not lines or lines[0].strip() != "---":
        return set()
    keys: set[str] = set()
    for line in lines[1:]:
        if line.strip() == "---":
            break
        if line[:1] in (" ", "\t"):  # indented → nested under a parent key, skip
            continue
        m = _FRONTMATTER_KEY.match(line)
        if m:
            keys.add(m.group(1))
    return keys


def scan_agent_frontmatter(target: Path) -> dict[str, set[str]]:
    """Map agent name -> the top-level frontmatter keys of its markdown def(s) under
    the target's `.opencode/agent[s]/`. An agent with a file but no frontmatter maps
    to an empty set (so callers can still tell the file EXISTS, which matters for the
    body-is-the-prompt case)."""
    found: dict[str, set[str]] = {}
    for sub in _AGENT_DIRS:
        directory = Path(target) / ".opencode" / sub
        if not directory.is_dir():
            continue
        for md in sorted(directory.glob("*.md")):
            keys = _frontmatter_keys(md.read_text(encoding="utf-8"))
            found.setdefault(md.stem, set()).update(keys)
    return found


def _danno_agent_fields(value: str | AgentSpec) -> set[str]:
    """OpenCode `agent.<name>` fields danno.toml sets for one agent. The string
    shorthand sets only `model`; the rich form sets each non-None field."""
    if isinstance(value, str):
        return {"model"}
    # `overrides` is the escape-hatch container, not an opencode agent field.
    return set(value.model_dump(exclude_none=True, exclude={"overrides"}))


def agent_markdown_collisions(config: DannoConfig, md_fields: dict[str, set[str]]) -> list[str]:
    """Loud warnings (Working Rule 8) for fields danno.toml sets that a markdown agent
    def ALSO sets and that danno does NOT route into the md itself. OpenCode resolves
    markdown over our generated JSON on conflict (verified), so such a value would be
    silently ignored — surface it. Fields in `_ROUTED_TO_MD` (model) are excluded: danno
    writes them into the md frontmatter where they win, so there is no shadow. `prompt`
    is special-cased: a markdown def's body IS the system prompt, so any markdown file
    shadows a danno-set `prompt`."""
    warnings: list[str] = []
    for agent, value in config.agents.items():
        if agent not in md_fields:
            continue
        danno_fields = _danno_agent_fields(value)
        clash = (danno_fields & md_fields[agent]) - _ROUTED_TO_MD
        if "prompt" in danno_fields:  # markdown body is always the prompt
            clash = clash | {"prompt"}
        if clash:
            shown = ", ".join(sorted(clash))
            warnings.append(
                f"agent '{agent}': danno.toml and .opencode/agent[s]/{agent}.md both set "
                f"{shown} — OpenCode's markdown wins, so danno's value(s) will be ignored. "
                "Set them in the markdown, or rename the danno agent."
            )
    return warnings


def _md_routed_agents(config: DannoConfig, md_fields: dict[str, set[str]]) -> frozenset[str]:
    """Agents whose model danno writes into their `.md` frontmatter: those that have a
    markdown def AND a model danno can resolve (markdown wins, so jsonc would be a no-op)."""
    return frozenset(
        agent
        for agent in config.agents
        if agent in md_fields and agent_model_name(config.agents[agent]) is not None
    )


def render_md_frontmatter_block(config: DannoConfig, value: str | AgentSpec) -> list[str]:
    """The danno-managed frontmatter lines for one agent (the routed assignment fields).

    Phase 1 routes only `model`. Returns an empty list when there is nothing to route
    (an agent with no model — e.g. a rich spec that only pins mode/permission)."""
    model = agent_model_name(value)
    if model is None:
        return []
    return [f"model: {agent_ref(config, model)}"]


def _agent_md_paths(target: Path, agent: str) -> list[Path]:
    """Existing `.md` def(s) for an agent across both dir spellings (both load in
    opencode, so danno edits each that exists)."""
    paths = []
    for sub in _AGENT_DIRS:
        p = Path(target) / ".opencode" / sub / f"{agent}.md"
        if p.is_file():
            paths.append(p)
    return paths


def _merge_md(existing: str, block_lines: list[str]) -> str:
    """Splice danno's managed frontmatter region into an agent `.md`, preserving every
    other frontmatter key AND the entire body verbatim. Replaces an existing managed
    region if present; else inserts it before the closing `---`; else (no frontmatter)
    creates a minimal `---` fence above the untouched body."""
    region = [_MD_BEGIN, *block_lines, _MD_END]
    lines = existing.splitlines()
    begin = end = None
    for i, ln in enumerate(lines):
        if _MD_BEGIN in ln:
            begin = i
        elif _MD_END in ln and begin is not None:
            end = i
            break
    if begin is not None and end is not None:
        return "\n".join([*lines[:begin], *region, *lines[end + 1 :]]) + "\n"
    if lines and lines[0].strip() == "---":
        for i in range(1, len(lines)):
            if lines[i].strip() == "---":  # insert just before the closing fence
                return "\n".join([*lines[:i], *region, *lines[i:]]) + "\n"
    return "\n".join(["---", *region, "---", *lines]) + "\n"


def _diff(existing: str, proposed: str, dest: Path) -> str:
    return "".join(
        difflib.unified_diff(
            existing.splitlines(keepends=True),
            proposed.splitlines(keepends=True),
            fromfile=str(dest),
            tofile="proposed",
        )
    )


def generate(
    config: DannoConfig,
    target: Path,
    *,
    apply: bool = False,
    disable_title: bool = False,
    agent_steps: dict[str, int] | None = None,
) -> GenerateResult:
    """Merge danno's managed region into <target>/.opencode/opencode.jsonc (Tier-1).

    Edits, not overwrites: only the bytes between the danno markers change; user keys
    and comments outside them survive. Model assignment for agents that have a `.md`
    def is routed out of here into the md (see `generate_md`). `disable_title` emits
    opencode's `agent.title.disable` — the validator passes it for sweeps so throwaway
    sessions don't run the local default model just to title threads."""
    md_fields = scan_agent_frontmatter(target)
    region_inner = _region_inner(
        config,
        _md_routed_agents(config, md_fields),
        disable_title=disable_title,
        agent_steps=agent_steps,
    )
    dest = Path(target) / ".opencode" / "opencode.jsonc"
    warnings = agent_markdown_collisions(config, md_fields) + override_warnings(config, "opencode")

    if dest.is_file():
        existing = dest.read_text(encoding="utf-8")
        merged = _merge_jsonc(existing, region_inner)
        if merged == existing:
            return GenerateResult(Action.UNCHANGED, dest, merged, warnings=warnings)
        diff = _diff(existing, merged, dest)
        if not apply:
            return GenerateResult(Action.DIFF, dest, merged, diff, warnings=warnings)
        dest.write_text(merged, encoding="utf-8")
        return GenerateResult(Action.WROTE, dest, merged, diff, warnings=warnings)

    # First run: nothing to clobber, so write the fresh managed file automatically.
    fresh = _fresh_jsonc(region_inner)
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(fresh, encoding="utf-8")
    return GenerateResult(Action.WROTE, dest, fresh, warnings=warnings)


def generate_md(config: DannoConfig, target: Path, *, apply: bool = False) -> list[GenerateResult]:
    """Merge danno's managed model-assignment region into each agent `.md` that controls
    an agent danno assigns a model to. One `GenerateResult` per edited file; same Tier-1
    semantics as `generate` (WROTE / UNCHANGED / DIFF). The body and all other
    frontmatter keys are preserved — danno owns only its marked frontmatter region."""
    results: list[GenerateResult] = []
    for agent, value in config.agents.items():
        block = render_md_frontmatter_block(config, value)
        if not block:
            continue
        for md_path in _agent_md_paths(target, agent):
            existing = md_path.read_text(encoding="utf-8")
            merged = _merge_md(existing, block)
            if merged == existing:
                results.append(GenerateResult(Action.UNCHANGED, md_path, merged))
                continue
            diff = _diff(existing, merged, md_path)
            if not apply:
                results.append(GenerateResult(Action.DIFF, md_path, merged, diff))
                continue
            md_path.write_text(merged, encoding="utf-8")
            results.append(GenerateResult(Action.WROTE, md_path, merged, diff))
    return results


# claurst's config filenames inside its HOME (`~/.claurst`). The overlay is pointed at
# by CLAURST_MODELS_PATH (read by the upstream binary); settings.json is claurst's own.
_CLAURST_MODELS_FILE = "models.json"
_CLAURST_SETTINGS_FILE = "settings.json"


def _emit_json(
    dest: Path, proposed: dict[str, Any], *, apply: bool, warnings: list[str] | None = None
) -> GenerateResult:
    """Write `proposed` as pretty JSON to `dest` with the same WROTE/UNCHANGED/DIFF
    advise/apply semantics as `generate`. A fresh file is written automatically (nothing
    to clobber); an existing file that would change needs `--apply`."""
    content = json.dumps(proposed, indent=2) + "\n"
    warns = warnings or []
    if dest.is_file():
        existing = dest.read_text(encoding="utf-8")
        if content == existing:
            return GenerateResult(Action.UNCHANGED, dest, content, warnings=warns)
        diff = _diff(existing, content, dest)
        if not apply:
            return GenerateResult(Action.DIFF, dest, content, diff, warnings=warns)
        dest.write_text(content, encoding="utf-8")
        return GenerateResult(Action.WROTE, dest, content, diff, warnings=warns)
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(content, encoding="utf-8")
    return GenerateResult(Action.WROTE, dest, content, warnings=warns)


def generate_claurst(
    config: DannoConfig, claurst_dir: Path, *, apply: bool = False
) -> list[GenerateResult]:
    """Generate claurst's config artifacts into `claurst_dir` (its `~/.claurst` HOME).

    The claurst peer of `generate`/`generate_md`. Two files, same Tier-1 advise/apply
    semantics (WROTE / UNCHANGED / DIFF):

    - **`models.json`** — the model-registry overlay (`generate_claurst_models`), pointed
      at by `CLAURST_MODELS_PATH`. danno owns this file wholesale (it is purely derived
      from danno.toml), so it is rewritten, not merged.
    - **`settings.json`** — claurst's own settings file, of which danno owns ONLY the
      `agents` key (`generate_claurst_agents`). Every other key a user set is preserved;
      danno replaces just `agents`. Unmappable [agents] fields are surfaced loud
      (`claurst_agent_unmapped_warnings`) on this result rather than silently dropped."""
    claurst_dir = Path(claurst_dir)
    # claurst override transparency (backend/model/agent) rides the models.json result —
    # a user-facing notice, not tied to one file's diff (see override_warnings).
    results = [
        _emit_json(
            claurst_dir / _CLAURST_MODELS_FILE,
            generate_claurst_models(config),
            apply=apply,
            warnings=override_warnings(config, "claurst"),
        )
    ]

    settings_dest = claurst_dir / _CLAURST_SETTINGS_FILE
    settings: dict[str, Any] = {}
    if settings_dest.is_file():
        loaded = json.loads(settings_dest.read_text(encoding="utf-8"))
        if isinstance(loaded, dict):  # preserve the user's other keys; own only `agents`
            settings = loaded
    settings["agents"] = generate_claurst_agents(config)
    results.append(
        _emit_json(
            settings_dest, settings, apply=apply, warnings=claurst_agent_unmapped_warnings(config)
        )
    )
    return results
