"""Generate <target>/.opencode/opencode.jsonc from a validated danno.toml.

Ports the agent-tier mapping from the Bash `tools/gen-opencode-config`. Tier-1 of
the automation policy: first run writes; a later run that would change the file
returns a diff for approval (the CLI requires --apply to write it).
"""

from __future__ import annotations

import difflib
import json
from dataclasses import dataclass
from enum import StrEnum
from pathlib import Path
from typing import Any

from .schema import CloudBackend, DannoConfig, LlamacppBackend, OllamaBackend

_HEADER = (
    "// Generated by book-em-danno (danno config generate) from danno.toml.\n"
    "// Edit danno.toml, not this file. Local agents need a TOOL-CAPABLE model\n"
    "// (gemma3:1b cannot tool-call).\n"
)

_LLAMACPP_STUB = "llama.cpp backend not yet implemented (stubbed slot in danno.toml)"


class Action(StrEnum):
    WROTE = "wrote"
    UNCHANGED = "unchanged"
    DIFF = "diff"  # differs from the existing file; not written (needs --apply)


@dataclass
class GenerateResult:
    action: Action
    path: Path
    content: str
    diff: str = ""


def _model_ref(config: DannoConfig, model_name: str) -> str:
    """Resolve a model name to its OpenCode `<provider>/<model>` reference."""
    model = config.models[model_name]
    backend = config.backends[model.backend]
    if isinstance(backend, OllamaBackend):
        if not model.tag:
            raise ValueError(f"model '{model_name}' on ollama backend needs a 'tag'")
        return f"{model.backend}/{model.tag}"
    if isinstance(backend, CloudBackend):
        if not model.id:
            raise ValueError(f"model '{model_name}' on cloud backend needs an 'id'")
        return model.id
    if isinstance(backend, LlamacppBackend):
        raise NotImplementedError(_LLAMACPP_STUB)
    raise ValueError(f"unknown backend kind for model '{model_name}'")


def render_config(config: DannoConfig) -> str:
    used_models = set(config.agents.values())

    # Emit a provider block for each ollama-kind backend referenced by a used model.
    providers: dict[str, dict[str, Any]] = {}
    for model_name in sorted(used_models):
        model = config.models[model_name]
        backend = config.backends[model.backend]
        if isinstance(backend, LlamacppBackend):
            raise NotImplementedError(_LLAMACPP_STUB)
        if isinstance(backend, OllamaBackend):
            provider = providers.setdefault(
                model.backend,
                {
                    "npm": "@ai-sdk/openai-compatible",
                    "name": f"{model.backend} (local)",
                    "options": {
                        "baseURL": backend.base_url,
                        "num_ctx": backend.num_ctx,
                        "apiKey": model.backend,
                    },
                    "models": {},
                },
            )
            provider["models"][model.tag] = {
                "name": f"{model.tag} (local)",
                "tool_call": model.tool_call,
                "limit": {"context": backend.num_ctx, "output": 8192},
            }

    agent_block = {
        agent: {"model": _model_ref(config, model_name)}
        for agent, model_name in config.agents.items()
    }

    default_agent = config.defaults.default_agent
    if default_agent in config.agents:
        main_ref = _model_ref(config, config.agents[default_agent])
    elif config.models:
        main_ref = _model_ref(config, sorted(config.models)[0])
    else:
        main_ref = ""

    # The small/cheap model: the first ollama-backed used model, else the main model.
    small_ref = main_ref
    for model_name in sorted(used_models):
        if isinstance(config.backends[config.models[model_name].backend], OllamaBackend):
            small_ref = _model_ref(config, model_name)
            break

    doc: dict[str, Any] = {
        "$schema": "https://opencode.ai/config.json",
        "default_agent": default_agent,
        "model": main_ref,
        "small_model": small_ref,
    }
    if providers:
        doc["provider"] = providers
    doc["agent"] = agent_block
    # OpenCode npm plugins: a bare package string, or the documented
    # [package, config] tuple when the plugin takes options. Omitted entirely for
    # plugin-less projects to keep the output minimal/stable.
    if config.npm:
        doc["plugin"] = [
            p.package if p.config is None else [p.package, p.config] for p in config.npm
        ]
    return _HEADER + json.dumps(doc, indent=2) + "\n"


def generate(
    config: DannoConfig,
    target: Path,
    *,
    apply: bool = False,
    dry_run: bool = False,
) -> GenerateResult:
    content = render_config(config)
    dest = Path(target) / ".opencode" / "opencode.jsonc"

    if dest.is_file():
        existing = dest.read_text(encoding="utf-8")
        if existing == content:
            return GenerateResult(Action.UNCHANGED, dest, content)
        diff = "".join(
            difflib.unified_diff(
                existing.splitlines(keepends=True),
                content.splitlines(keepends=True),
                fromfile=str(dest),
                tofile="proposed",
            )
        )
        if dry_run or not apply:
            return GenerateResult(Action.DIFF, dest, content, diff)
        dest.write_text(content, encoding="utf-8")
        return GenerateResult(Action.WROTE, dest, content, diff)

    # First run: nothing to clobber, so write automatically (unless dry-run).
    if dry_run:
        return GenerateResult(Action.DIFF, dest, content, content)
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(content, encoding="utf-8")
    return GenerateResult(Action.WROTE, dest, content)
