"""Generate <target>/.opencode/opencode.jsonc from a validated danno.toml.

Ports the agent-tier mapping from the Bash `tools/gen-opencode-config`. Tier-1 of
the automation policy: a new file is written freely on first run (nothing to
clobber); a later run that would change an existing file returns a diff for
approval (the CLI requires --apply to overwrite it).
"""

from __future__ import annotations

import difflib
import json
import re
from dataclasses import dataclass, field
from enum import StrEnum
from pathlib import Path
from typing import Any

from .schema import AgentSpec, DannoConfig, LlamacppBackend, OllamaBackend, OpenAIBackend

_HEADER = (
    "// Generated by book-em-danno (danno config generate) from danno.toml. Edit danno.toml.\n"
    "// models.<tag>.limit.context : OpenCode's CLIENT-SIDE belief of the window, used to\n"
    "//                              trim/compact the conversation. From danno's context_budget.\n"
    "//                              It does NOT set Ollama's real window: under /v1 Ollama\n"
    "//                              loads the model at its FULL context (a body num_ctx is\n"
    "//                              ignored). The real window / RAM lever is an Ollama\n"
    "//                              Modelfile variant, not an opencode.jsonc key.\n"
    "// models.<tag>.limit.output  : tokens OpenCode reserves for the reply\n"
    "//                              (usable input is roughly context - output).\n"
    "// models.<tag>.options.reasoningEffort : forwarded raw into the /v1 request body where\n"
    "//                              Ollama honors it. 'none' disables the thinking trace\n"
    "//                              (faster; avoids the opencode #21903 reasoning-field hang).\n"
    "// opencode ALWAYS streams (stream:true is hardcoded); there is no stream/thinking key.\n"
    "// Local agents need a TOOL-CAPABLE model (gemma3:1b cannot tool-call).\n"
)

_LLAMACPP_STUB = "llama.cpp backend not yet implemented (stubbed slot in danno.toml)"


class Action(StrEnum):
    WROTE = "wrote"
    UNCHANGED = "unchanged"
    DIFF = "diff"  # differs from the existing file; not written (needs --apply)


@dataclass
class GenerateResult:
    action: Action
    path: Path
    content: str
    diff: str = ""
    warnings: list[str] = field(default_factory=list)


def model_ref(config: DannoConfig, model_name: str) -> str:
    """Resolve a model name to its OpenCode `<provider>/<model>` reference.

    Public so the validator's matrix generator can label and `-m`-drive each model
    variant with the exact ref OpenCode expects (e.g. `ollama/gemma3:27b`)."""
    model = config.models[model_name]
    backend = config.backends[model.backend]
    if isinstance(backend, OllamaBackend | OpenAIBackend):
        if not model.tag:
            raise ValueError(f"model '{model_name}' on {backend.kind} backend needs a 'tag'")
        return f"{model.backend}/{model.tag}"
    if isinstance(backend, LlamacppBackend):
        raise NotImplementedError(_LLAMACPP_STUB)
    raise ValueError(f"unknown backend kind for model '{model_name}'")


def agent_ref(config: DannoConfig, value: str) -> str:
    """Resolve an [agents] model value to an OpenCode model ref.

    A value with a '/' is a raw OpenCode ref (e.g. `anthropic/claude-sonnet-4-6`),
    passed through verbatim — OpenCode knows built-in cloud models via its catalog
    and launch-time auth, so danno emits no provider block for them. A value without
    a '/' names a [models] entry resolved via `model_ref`."""
    if "/" in value:
        return value
    return model_ref(config, value)


def agent_model_name(value: str | AgentSpec) -> str | None:
    """The danno model NAME (or raw ref) an [agents] value selects, in either form.

    The string shorthand IS the name; the rich form carries it in `.model` (which may
    be unset when the agent only pins mode/permission). Distinct from `agent_ref`,
    which RESOLVES a name to its OpenCode ref."""
    return value if isinstance(value, str) else value.model


def render_config(config: DannoConfig) -> str:
    # Model NAMES the agent map selects, in either [agents] form (raw refs included).
    used_models = {
        name for value in config.agents.values() if (name := agent_model_name(value)) is not None
    }

    # Emit a provider block for every ollama-kind model DEFINED in danno.toml, not
    # just those assigned to an agent — so the whole catalog shows in opencode's
    # model picker (the user switches models interactively, beyond the agent map).
    providers: dict[str, dict[str, Any]] = {}
    for model_name in sorted(config.models):
        model = config.models[model_name]
        backend = config.backends[model.backend]
        if isinstance(backend, LlamacppBackend):
            raise NotImplementedError(_LLAMACPP_STUB)
        if isinstance(backend, OllamaBackend | OpenAIBackend):
            # Both render an @ai-sdk/openai-compatible provider; they differ only in
            # auth and labelling: ollama is local/no-auth (dummy apiKey = the backend
            # name), openai-compatible carries an env-substituted key.
            if isinstance(backend, OllamaBackend):
                provider_name = f"{model.backend} (local)"
                api_key = model.backend
                model_label = f"{model.tag} (local)"
            else:  # OpenAIBackend — secret arrives at runtime, never written here
                provider_name = model.backend
                api_key = f"{{env:{backend.api_key_env}}}"
                model_label = model.tag or ""
            provider = providers.setdefault(
                model.backend,
                {
                    "npm": "@ai-sdk/openai-compatible",
                    "name": provider_name,
                    "options": {"baseURL": backend.base_url, "apiKey": api_key},
                    "models": {},
                },
            )
            entry: dict[str, Any] = {
                "name": model_label,
                "tool_call": model.tool_call,
                "limit": {"context": backend.context_budget, "output": backend.output_limit},
            }
            if model.reasoning_effort is not None:
                # camelCase is load-bearing: @ai-sdk/openai-compatible spreads model
                # options raw into the body, and a snake_case key gets clobbered.
                entry["options"] = {"reasoningEffort": model.reasoning_effort}
            provider["models"][model.tag] = entry

    # Each agent renders to its opencode.jsonc `agent.<name>` block. The string
    # shorthand is just a model; the rich form's other fields are emitted verbatim
    # (its `model`, if set, resolved to a ref the same way).
    agent_block: dict[str, dict[str, Any]] = {}
    for agent, value in config.agents.items():
        if isinstance(value, str):
            agent_block[agent] = {"model": agent_ref(config, value)}
            continue
        entry = value.model_dump(exclude_none=True)
        if value.model is not None:
            entry["model"] = agent_ref(config, value.model)
        agent_block[agent] = entry

    default_agent = config.defaults.default_agent
    default_model = (
        agent_model_name(config.agents[default_agent]) if default_agent in config.agents else None
    )
    if default_model is not None:
        main_ref = agent_ref(config, default_model)
    elif config.models:
        main_ref = model_ref(config, sorted(config.models)[0])
    else:
        main_ref = ""

    # The small/cheap model: the first ollama-backed used model, else the main model.
    # Raw refs (anthropic/…) aren't [models] entries, so skip them — they have no
    # local backend to qualify as the small model.
    small_ref = main_ref
    for value in sorted(used_models):
        if "/" in value or value not in config.models:
            continue
        if isinstance(config.backends[config.models[value].backend], OllamaBackend):
            small_ref = model_ref(config, value)
            break

    doc: dict[str, Any] = {
        "$schema": "https://opencode.ai/config.json",
        "default_agent": default_agent,
        "model": main_ref,
        "small_model": small_ref,
    }
    if providers:
        doc["provider"] = providers
    doc["agent"] = agent_block
    # OpenCode npm plugins: a bare package string, or the documented
    # [package, config] tuple when the plugin takes options. Omitted entirely for
    # plugin-less projects to keep the output minimal/stable.
    if config.npm:
        doc["plugin"] = [
            p.package if p.config is None else [p.package, p.config] for p in config.npm
        ]
    return _HEADER + json.dumps(doc, indent=2) + "\n"


# Markdown agent defs live under either dir (docs use plural, ADOS uses singular);
# OpenCode loads BOTH, so danno scans both. danno NEVER writes these files.
_AGENT_DIRS = ("agents", "agent")

_FRONTMATTER_KEY = re.compile(r"([A-Za-z_][\w-]*):")


def _frontmatter_keys(md_text: str) -> set[str]:
    """The top-level YAML frontmatter keys of a markdown agent def.

    Only the key NAMES are needed (to detect which fields a markdown def sets), so a
    top-level `^key:` scan of the leading `---`-fenced block is enough — no YAML
    dependency, and nested/indented keys are intentionally skipped."""
    lines = md_text.splitlines()
    if not lines or lines[0].strip() != "---":
        return set()
    keys: set[str] = set()
    for line in lines[1:]:
        if line.strip() == "---":
            break
        if line[:1] in (" ", "\t"):  # indented → nested under a parent key, skip
            continue
        m = _FRONTMATTER_KEY.match(line)
        if m:
            keys.add(m.group(1))
    return keys


def scan_agent_frontmatter(target: Path) -> dict[str, set[str]]:
    """Map agent name -> the top-level frontmatter keys of its markdown def(s) under
    the target's `.opencode/agent[s]/`. An agent with a file but no frontmatter maps
    to an empty set (so callers can still tell the file EXISTS, which matters for the
    body-is-the-prompt case)."""
    found: dict[str, set[str]] = {}
    for sub in _AGENT_DIRS:
        directory = Path(target) / ".opencode" / sub
        if not directory.is_dir():
            continue
        for md in sorted(directory.glob("*.md")):
            keys = _frontmatter_keys(md.read_text(encoding="utf-8"))
            found.setdefault(md.stem, set()).update(keys)
    return found


def _danno_agent_fields(value: str | AgentSpec) -> set[str]:
    """OpenCode `agent.<name>` fields danno.toml sets for one agent. The string
    shorthand sets only `model`; the rich form sets each non-None field."""
    if isinstance(value, str):
        return {"model"}
    return set(value.model_dump(exclude_none=True))


def agent_markdown_collisions(config: DannoConfig, md_fields: dict[str, set[str]]) -> list[str]:
    """Loud warnings (Working Rule 8) for fields danno.toml sets that a markdown agent
    def ALSO sets. OpenCode resolves markdown over our generated JSON on any conflict
    (verified), so a shadowed danno.toml value would be silently ignored — surface it
    instead of emitting a lie. `prompt` is special-cased: a markdown def's body IS the
    system prompt, so any markdown file shadows a danno-set `prompt`."""
    warnings: list[str] = []
    for agent, value in config.agents.items():
        if agent not in md_fields:
            continue
        danno_fields = _danno_agent_fields(value)
        clash = danno_fields & md_fields[agent]
        if "prompt" in danno_fields:  # markdown body is always the prompt
            clash = clash | {"prompt"}
        if clash:
            shown = ", ".join(sorted(clash))
            warnings.append(
                f"agent '{agent}': danno.toml and .opencode/agent[s]/{agent}.md both set "
                f"{shown} — OpenCode's markdown wins, so danno's value(s) will be ignored. "
                "Set them in the markdown, or rename the danno agent."
            )
    return warnings


def generate(
    config: DannoConfig,
    target: Path,
    *,
    apply: bool = False,
) -> GenerateResult:
    content = render_config(config)
    dest = Path(target) / ".opencode" / "opencode.jsonc"
    warnings = agent_markdown_collisions(config, scan_agent_frontmatter(target))

    if dest.is_file():
        existing = dest.read_text(encoding="utf-8")
        if existing == content:
            return GenerateResult(Action.UNCHANGED, dest, content, warnings=warnings)
        diff = "".join(
            difflib.unified_diff(
                existing.splitlines(keepends=True),
                content.splitlines(keepends=True),
                fromfile=str(dest),
                tofile="proposed",
            )
        )
        if not apply:
            return GenerateResult(Action.DIFF, dest, content, diff, warnings=warnings)
        dest.write_text(content, encoding="utf-8")
        return GenerateResult(Action.WROTE, dest, content, diff, warnings=warnings)

    # First run: nothing to clobber, so write automatically.
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(content, encoding="utf-8")
    return GenerateResult(Action.WROTE, dest, content, warnings=warnings)
